# Generated by Django 5.1.2 on 2024-10-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='p_no',
            new_name='position',
        ),
    ]
