# Generated by Django 5.1.2 on 2024-10-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_p_no_productgallery_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
