# Generated by Django 5.1.2 on 2024-10-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('currency_type', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('is_default', models.BooleanField(default=False)),
                ('countries', models.ManyToManyField(blank=True, related_name='countries', to='address.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
